## Fasttext

In [46]:
import fasttext
import os
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
DATASET_DIR = '../dataset/8_fasttext/'
TRAIN_LIST = DATASET_DIR + 'train.csv'
VAL_LIST = DATASET_DIR + 'val.csv'
TEST_LIST = DATASET_DIR + 'test.csv'


## Train Model
> Uses autotune-hyperparameter option to find best model

In [4]:
model = fasttext.train_supervised(input=TRAIN_LIST, autotuneValidationFile=VAL_LIST, verbose=1)

In [42]:
dF = pd.read_csv(TEST_LIST, header=None, names=['labels', 'text'], sep=' ')
test_labels = dF.labels
pred_labels = []

for each in dF.text:
    pred_labels.append(model.predict(each)[0][0])

In [43]:
def parse_labels(path):
    with open(path, 'r') as f:
        return np.array(list(map(lambda x: x[9:], f.read().split())))

In [44]:
eq = test_labels == pred_labels
print("Accuracy: " + str(eq.sum() / len(test_labels)))
print(confusion_matrix(test_labels, pred_labels))

Accuracy: 0.8585966791644349
[[1391   52  104   19   70]
 [  56 1499  172   56  117]
 [  51   76 2061   35  160]
 [  14   45   59 3103   46]
 [  61  116  228   47 1564]]


In [48]:
print(classification_report(test_labels, pred_labels))

                        precision    recall  f1-score   support

__label__fawadchaudhry       0.88      0.85      0.87      1636
__label__maryamnsharif       0.84      0.79      0.81      1900
 __label__mjibrannasir       0.79      0.86      0.82      2383
 __label__narendramodi       0.95      0.95      0.95      3267
 __label__sherryrehman       0.80      0.78      0.79      2016

              accuracy                           0.86     11202
             macro avg       0.85      0.85      0.85     11202
          weighted avg       0.86      0.86      0.86     11202

